# Generated by Django 3.2.4 on 2022-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220902_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20)),
                ('ppic', models.ImageField(null=True, upload_to='static/profile')),
                ('passwd', models.CharField(max_length=70)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='maincate',
            name='picture',
            field=models.ImageField(default='', upload_to='static/mcategory/'),
        ),
    ]
