# Generated by Django 3.2.4 on 2022-09-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220904_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=60)),
                ('pid', models.IntegerField()),
                ('cdate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='morder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('odate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='mobile',
            new_name='Mobile',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='passwd',
            new_name='Passwd',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='ppic',
            new_name='Ppic',
        ),
    ]
