# Generated by Django 3.2.4 on 2022-09-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220905_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcart',
            name='cdate',
            field=models.CharField(max_length=60),
        ),
    ]
