# Generated by Django 3.2.4 on 2022-09-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_mcart_cdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mcart',
            new_name='mycart',
        ),
    ]
