# Generated by Django 6.0.6 on 2026-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_mycart_mcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Passwd',
            field=models.CharField(max_length=128),
        ),
    ]
